using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.InputSystem;
using CriWare;

// ï¿½ï¿½ï¿½Ì‚Qï¿½sï¿½ÌƒRï¿½[ï¿½hï¿½ÅƒRï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½É’Ç‰ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½B
[RequireComponent(typeof(CharacterController))]
public class Sound : MonoBehaviour
{
   /* public AudioSource audioSource;
    public List<AudioClip> audioClipList = new List<AudioClip>();

    [SerializeField] private AudioSource a;//AudioSourceï¿½^ï¿½Ì•Ïï¿½aï¿½ï¿½éŒ¾ ï¿½gï¿½pï¿½ï¿½ï¿½ï¿½AudioSourceï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ï¿½Aï¿½^ï¿½bï¿½`ï¿½Kï¿½v

    [SerializeField] private AudioClip walk;//AudioClipï¿½^ï¿½Ì•Ïï¿½b1ï¿½ï¿½éŒ¾ ï¿½gï¿½pï¿½ï¿½ï¿½ï¿½AudioClipï¿½ï¿½ï¿½Aï¿½^ï¿½bï¿½`ï¿½Kï¿½v
    [SerializeField] private AudioClip ball;

    */

    
/* (2) ãƒ—ãƒ¬ãƒ¼ãƒ¤ãƒ¼ */
   // private CriAtomExPlayer walk;
   private CriAtomExPlayer walk;


    /* (12) ACB æƒ…å ± */
    private CriAtomExAcb acb;

    /* (16) ã‚­ãƒ¥ãƒ¼å */
    private string cueName;

    

public void Play()
    {
    if (Keyboard.current.wKey.wasPressedThisFrame || Keyboard.current.aKey.wasPressedThisFrame || Keyboard.current.sKey.wasPressedThisFrame || Keyboard.current.dKey.wasPressedThisFrame)//ï¿½Ú“ï¿½ï¿½ï¿½   
        {
            if (index == 0)  //ï¿½lï¿½^ï¿½ï¿½Ôï¿½
            {
             
                /* (7) ãƒ—ãƒ¬ãƒ¼ãƒ¤ãƒ¼ã®å†ç”Ÿ */
               // walk.Start("walk_nomal_R");
            }
        }
    
    }

//å‰ã®éŸ³å†ç”Ÿã™ã‚‹ã‚„ã¤
    /*    private void OnSound()
    {
        

        if (Keyboard.current.wKey.wasPressedThisFrame || Keyboard.current.aKey.wasPressedThisFrame || Keyboard.current.sKey.wasPressedThisFrame || Keyboard.current.dKey.wasPressedThisFrame)//ï¿½Ú“ï¿½ï¿½ï¿½
        {
            if (index == 0)  //ï¿½lï¿½^ï¿½ï¿½Ôï¿½
            {
                a.PlayOneShot(walk);
            }
            if (index == 1)  //ï¿½ï¿½Êï¿½Ôï¿½
            {
                a.PlayOneShot(ball);
            }
        }
        if (Keyboard.current.spaceKey.wasPressedThisFrame)//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½
        {

        }
        if (Grider)//ï¿½Oï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½gï¿½pï¿½ï¿½
        {

        }
    }*/
    // Start is called before the first frame update
    Rigidbody rb;
    public float speed = 1.0f;//ï¿½ï¿½ï¿½ï¿½ï¿½x
    public float LimitSpeed = 50.0f;//ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½
    public float Jump = 10.0f;//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½
    public float TimeCount;//ï¿½ï¿½ï¿½ï¿½ï¿½ñ•œƒCï¿½ï¿½ï¿½^ï¿½[ï¿½oï¿½ï¿½
    public int HP;//?ï¿½ï¿½ï¿½l
    public int HPmax;
    public int GaugeQuantity;
    public int mushi;//ï¿½ï¿½å³‚Ì‰ñ”ï¿½ï¿½ï¿½
    public int index = 0;//ï¿½lï¿½Æï¿½Ê‚ÌØ‚ï¿½Ö‚ï¿½
    private int o_max = 0;

    public Vector3 Rotate;

    public Slider GaugeMain;//ï¿½eï¿½Qï¿½[ï¿½W
    public Slider Gauge2;
    public Slider Gauge3;
    public GameObject UI3;

    public bool Ground;//ï¿½nï¿½Ê‚Æ‚ÌÚGï¿½ï¿½ï¿½ï¿½
    public bool Grider;//ï¿½Oï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½gï¿½pï¿½ï¿½ï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½
    public bool Count;//ï¿½ñ•œƒCï¿½ï¿½ï¿½^ï¿½[ï¿½oï¿½ï¿½ï¿½Ç—ï¿½

    public GameObject body;
    public GameObject Ice;
    public GameObject JumpPadPrefab;
    GameObject[] childObject;

    private Vector3 bodyHeight = new Vector3(0.0f, -1.000001f, 0.0f);  //ï¿½Xï¿½ğ¶ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½ÉŠÖŒWï¿½Bï¿½Ì‚Ì‘å‚«ï¿½ï¿½ï¿½Æ•Xï¿½ÌŒï¿½ï¿½ï¿½ï¿½ÉˆË‘ï¿½

    RaycastHit hit;

    //InputSystem
    private InputAction moveAction;
    private InputAction lookAction;
    private Vector2 Move;
    public Vector2 Look;

    Vector2 Aspeed = Vector2.zero;

    void Start()
    {
        rb = GetComponent<Rigidbody>();
        Ground = true;

        GaugeQuantity = 2;
        GaugeMain.value = 100;
        GaugeMain.maxValue = 100;
        Gauge2.value = 0;
        Gauge2.maxValue = 100;
        Gauge3.value = 0;
        Gauge3.maxValue = 100;
        HP = 100;
        HPmax = 100 * GaugeQuantity;
        mushi = 1;
        TimeCount = 3.0f;
        Count = true;

        Rotate = Vector3.zero;

        o_max = this.transform.childCount;//ï¿½qï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ÌŒÂï¿½ï¿½æ“¾
        childObject = new GameObject[o_max];//ï¿½Cï¿½ï¿½ï¿½Xï¿½^ï¿½ï¿½ï¿½Xï¿½ì¬

        for (int i = 0; i < o_max; i++)
        {
            childObject[i] = transform.GetChild(i).gameObject;//ï¿½ï¿½ï¿½×‚Ä‚Ìqï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½æ“¾
        }
        //ï¿½ï¿½ï¿½×‚Ä‚Ìqï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½Aï¿½Nï¿½eï¿½Bï¿½u
        foreach (GameObject gamObj in childObject)
        {
            gamObj.SetActive(false);
        }
        //ï¿½Åï¿½ï¿½Í‚Ğ‚Æ‚Â‚ï¿½ï¿½ï¿½ï¿½Aï¿½Nï¿½eï¿½Bï¿½uï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        childObject[index].SetActive(true);
        //InputSystem
        var pInput = GetComponent<PlayerInput>();
        var actionMap = pInput.currentActionMap;

        moveAction = actionMap["Move"];
        lookAction = actionMap["Look"];

        //ä»¥ä¸‹ã‚µã‚¦ãƒ³ãƒ‰é–¢ä¿‚

        /* (5) ãƒ—ãƒ¬ãƒ¼ãƒ¤ãƒ¼ã®ä½œæˆ */
        walk = new CriAtomExPlayer();

        
    }

    // Update is called once per frame
    void Update()
    {
       // OnSound();
        Move = moveAction.ReadValue<Vector2>();//ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ì‘€ï¿½ï¿½æ“¾
        Look = lookAction.ReadValue<Vector2>();//ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½æ“¾

        debugcom();
        ConnectIce();
        //Freez();
        HPGaugeControl();

        Aspeed = new Vector2(rb.velocity.x, rb.velocity.z);//ï¿½ï¿½ï¿½xï¿½xï¿½Nï¿½gï¿½ï¿½

        if (Ground == true || Grider == true)//ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            MoveControroller();
        }

        if ((Mathf.Abs(Aspeed.magnitude) >= LimitSpeed))//ï¿½Å‘å‘¬ï¿½x
        {
            Vector3 Vero = new Vector3(rb.velocity.x, 0.0f, rb.velocity.z);
            rb.velocity = Vero.normalized * LimitSpeed;
        }

        if (Input.GetKey("left shift"))
        {
            speed = 200.0f;
            //if (HP >= 1)
            //    rb.AddForce(0.0f, -1 * rb.velocity.y, 0.0f, ForceMode.VelocityChange);
        }
        else
        {
            speed = 100.0f;
        }

        if (Input.GetKey("space") && Ground == true)
        {
            rb.AddForce(0.0f, Jump, 0.0f, ForceMode.Impulse);
            Ground = false;
        }

        if (Input.GetKey("1") && mushi == 1)
        {
            Ground = false;
            rb.constraints = RigidbodyConstraints.FreezeRotation;
            rb.velocity = Vector3.zero;
            rb.AddForce(0.0f, 8.0f, 5.0f, ForceMode.Impulse);
            mushi = 0; ;
            Ground = false;
        }
        if (Input.GetMouseButtonDown(1) && Ground == false)
        {
            if (Grider == false)
            {
                rb.drag = 8;
                Grider = true;
            }
            else
            {
                rb.drag = 0.5f;
                Grider = false;
            }
        }
    }

    private void FixedUpdate()
    {
        Vector3 cameraForward = Vector3.Scale(Camera.main.transform.forward, new Vector3(1, 0, 1)).normalized;
        // ï¿½ï¿½ï¿½ï¿½ï¿½Lï¿½[ï¿½Ì“ï¿½ï¿½Í’lï¿½ÆƒJï¿½ï¿½ï¿½ï¿½ï¿½ÌŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        Vector3 moveForward = cameraForward * Move.y + Camera.main.transform.right * Move.x;

        // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉƒXï¿½sï¿½[ï¿½hï¿½ï¿½ï¿½|ï¿½ï¿½ï¿½ï¿½Bï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½â—ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ÍAï¿½Ê“rYï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½xï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½ğ‘«‚ï¿½ï¿½B
        //rb.velocity = moveForward * speed + new Vector3(0, rb.velocity.y, 0);
        if (moveForward != Vector3.zero)
        {
            transform.rotation = Quaternion.LookRotation(moveForward);
        }
    }
    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.tag == "Ground")//ï¿½nï¿½Ê‚Æ‚ÌÚGï¿½ï¿½ï¿½ï¿½
        {
            Ground = true;
            Grider = false;
            rb.drag = 0.5f;
            mushi = 1;
        }
        if (collision.gameObject.tag == "JumpPad")//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½
        {
            rb.AddForce(0, Jump, 0, ForceMode.Impulse);
            Ground = false;
        }
        if (collision.gameObject.tag == "BrokenObject")
        {
            Destroy(collision.gameObject);
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("heal") == true)//ï¿½ñ•œƒAï¿½Cï¿½eï¿½ï¿½
        {
            HP += 100;
            Destroy(other.gameObject);
        }
    }

    void MoveControroller()//ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½Nï¿½ï¿½ï¿½vï¿½g
    {
        rb.constraints = RigidbodyConstraints.FreezeRotationX;
        rb.constraints |= RigidbodyConstraints.FreezeRotationZ;
        //if ((Mathf.Abs(Aspeed.magnitude) < LimitSpeed)){
        rb.AddRelativeForce(0.0f, 0.0f, Move.magnitude * speed, ForceMode.Force);
    }
    public void JumpController(InputAction.CallbackContext context)
    {
        if (context.started)
        {
            if (index == 0)
            {
                if (Ground)
                {
                    rb.AddForce(0.0f, Jump, 0.0f, ForceMode.Impulse);
                    Ground = false;
                }
                else if (Ground == false)
                {
                    if (Grider == false)
                    {
                        rb.drag = 8;
                        Grider = true;
                    }
                    else
                    {
                        rb.drag = 0.5f;
                        Grider = false;
                    }
                }
            }
        }
    }
    private void Freez()//WASDï¿½ï¿½ï¿½Í‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½j
    {
        if (Move.magnitude == 0 || Ground == true)
        {
            rb.constraints |= RigidbodyConstraints.FreezePositionX;
            rb.constraints |= RigidbodyConstraints.FreezePositionZ;
        }
    }


    void ConnectIce()
    {
        if (Input.GetKey(KeyCode.LeftShift)) //ï¿½_ï¿½bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½ó’†‚É‚ï¿½ï¿½ï¿½Î•Xï¿½Ìï¿½ï¿½ğ¶ï¿½
        {
            if (Physics.Raycast(body.transform.position, Vector3.down, out hit, 1.1f) == false && Ground && HP > 1)
            {
                rb.AddForce(0.0f, -1 * rb.velocity.y, 0.0f, ForceMode.VelocityChange);
                Vector3 horisonMove = new Vector3(rb.velocity.x, 0.0f, rb.velocity.z);
                Vector3 verticalMove = new Vector3(0.0f, rb.velocity.y, 0.0f);

                Vector3 IcePosition = body.transform.position + bodyHeight + horisonMove.normalized * 2.5f;
                Instantiate(Ice, IcePosition, Quaternion.identity);  //ï¿½Xï¿½Ìï¿½ï¿½ğ¶ï¿½
                HP -= 1;//ï¿½İ’uï¿½ï¿½ï¿½ï¿½ï¿½HPï¿½ï¿½-1ï¿½ï¿½ï¿½ï¿½ï¿½
                TimeCount = 3.0f;
            }
        }
    }

    void HPGaugeControl()
    {
        if (Input.GetKey(KeyCode.Q) & HP >= 10)
        {
            HP -= 10;
            TimeCount = 3.0f;
        }

        if (Input.GetKey(KeyCode.O) & GaugeQuantity < 3)//HPï¿½oï¿½[ï¿½ï¿½ï¿½ï¿½
        {
            UI3.SetActive(true);
            GaugeQuantity++;
            HPmax = 100 * GaugeQuantity;
        }
        if (HP > HPmax)//ï¿½Å‘ï¿½HPï¿½ï¿½ï¿½ï¿½
        {
            HP = HPmax;
        }
        if (HP < 100 & Count == false)//ï¿½ï¿½ï¿½ï¿½ï¿½ñ•œ‚Æï¿½ï¿½ï¿½
        {
            HP = HP + 1;
        }
        GaugeMain.value = HP;//UIï¿½Ì•ÏX
        Gauge2.value = HP - 100;
        Gauge3.value = HP - 200;
        if (TimeCount > 0.0f)//ï¿½ï¿½ï¿½ï¿½ï¿½ñ•œ‚ÌƒCï¿½ï¿½ï¿½^ï¿½[ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        {
            TimeCount -= Time.deltaTime;
            Count = true;
        }
        else
        {
            Count = false;
        }
    }

    public void Change(InputAction.CallbackContext context)
    {
        //ï¿½ï¿½ï¿½İ‚ÌƒAï¿½Nï¿½eï¿½Bï¿½uï¿½Èqï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½Aï¿½Nï¿½eï¿½Bï¿½u
        childObject[index].SetActive(false);
        if (context.started)
        {
            LimitSpeed = 50;
            index = 1;
            rb.mass = 10;
        }
        if (context.canceled)
        {
            LimitSpeed = 25;
            index = 0;
            rb.mass = 50;
        }
        //ï¿½ï¿½ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½Aï¿½Nï¿½eï¿½Bï¿½uï¿½ï¿½
        childObject[index].SetActive(true);
    }
    public void Mushi(InputAction.CallbackContext context)
    {
        if (context.started)
        {
            if (mushi == 1)
            {
                Ground = false;
                rb.constraints = RigidbodyConstraints.FreezeRotation;
                rb.velocity = Vector3.zero;
                rb.AddForce(0.0f, 8.0f, 5.0f, ForceMode.Impulse);
                mushi = 0; ;
                Ground = false;
            }
        }
    }
    public void JumpPadSet(InputAction.CallbackContext context)//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½İ’u
    {
        if (context.started)
        {
            if (Ground && HP >= 10)
            {
                Vector3 PadPosition = transform.position + 3.0f * Vector3.down + rb.velocity.normalized * 3.0f;
                Instantiate(JumpPadPrefab, PadPosition, transform.rotation * Quaternion.AngleAxis(180, Vector3.up));
                HP -= 10;
                TimeCount = 3.0f;
            }
        }
    }

    void debugcom()
    {
        //Debug.Log(index);
        //Debug.Log(rb.velocity.magnitude);
        //Debug.Log(Move);
        Debug.Log(Move.magnitude);
    }
}
